"""MAP_INDEX.md (Layer 2) must be FRESH — the mechanical replacement for hand-classification.

Layer 2 is auto-generated by scripts/gen_map_index.py by walking the filesystem, so it is complete on
files and can never omit a new one — PROVIDED it's regenerated when files change. This fails the build
if MAP_INDEX.md is stale, so a forgotten regenerate can't ship. This is what dissolves the old
MAP-IGNORE judgment (the 2026-06-19 failure): no human decides what's listed anymore.

Fix on failure:  python scripts/gen_map_index.py
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def test_map_index_is_fresh():
    r = subprocess.run([sys.executable, os.path.join("scripts", "gen_map_index.py"), "--check"],
                       cwd=ROOT, capture_output=True, text=True)
    assert r.returncode == 0, ("MAP_INDEX.md is STALE — run: python scripts/gen_map_index.py\n"
                               + (r.stdout or "") + (r.stderr or ""))
