"""wizard.card_details — what each capability would contain, by INDUSTRY STANDARD. A reference MENU the owner
reviews to decide what to wire next (not the live config — the editor is that; this is "what could be inside"
per card, with our current coverage marked). status: built | planned | idea.
"""

# key → {icon, title, what, ref (who does this well), configure (link to the functional page if any), options}
CARD_DETAILS = {
    "accountant": {
        "icon": "🍚", "title": "Accountant / Bookkeeping",
        "what": "Receipts and bills → clean books: expenses, suppliers, payables, food allowance.",
        "ref": "QuickBooks · Xero · Wave", "configure": "/expenses",
        "options": [
            ("Receipt capture (OCR)", "Snap a photo → items + total read automatically (deterministic, Khmer-aware)", "built"),
            ("Vendors & suppliers", "Supplier list with dedup, aliases, contact + payment terms", "built"),
            ("Bills & payables", "Due dates, reminders, the recurring payable run + once-off market buys", "built"),
            ("Food allowance", "Auto staff meal money from scheduled hours (riel rate ÷ FX)", "built"),
            ("Expense categories", "Chart of accounts / categories per expense", "planned"),
            ("Invoices & receivables", "Bill customers, track who owes you", "planned"),
            ("Bank / cash reconciliation", "Match recorded spend to bank or cash on hand", "planned"),
            ("P&L · cash-flow reports", "Standard financial statements over time", "planned"),
            ("Tax / VAT tracking", "Input/output tax + returns", "idea"),
            ("Multi-currency", "USD / KHR side by side", "idea"),
        ],
    },
    "stock": {
        "icon": "📦", "title": "Stock / Inventory",
        "what": "Know what you have, never run out, buy from the cheapest.",
        "ref": "Lightspeed · StoreHub · Sortly · Loyverse", "configure": "/stock",
        "options": [
            ("Stock counts", "Cycle + full counts (paperless / photo / AppSheet)", "built"),
            ("Par / reorder levels", "Target per item → reorder nudge before you run out", "built"),
            ("Supplier price compare", "Each item's price across suppliers → cheapest flagged", "built"),
            ("Low-stock & expiry alerts", "Warn before a stockout or spoilage", "built"),
            ("Item catalog", "SKUs, categories, units, photos", "planned"),
            ("Purchase orders", "Build + send order lists to suppliers", "planned"),
            ("Stock movements", "In / out / waste / transfer between locations", "planned"),
            ("Barcode / QR", "Scan to count or sell", "idea"),
            ("Recipes / BOM", "Ingredients per menu item (auto-deduct on sale)", "idea"),
            ("Valuation", "FIFO / average cost, total stock value", "idea"),
        ],
    },
    "pos": {
        "icon": "🛒", "title": "POS / Point of sale",
        "what": "Ring up sales on any device — or tap your existing till — tied into stock + books.",
        "ref": "Square · Toast · Loyverse · StoreHub", "configure": "/customer/config",
        "options": [
            ("Be the POS or tap existing", "Use ours, or read sales from Loyverse / Square", "built"),
            ("Payments", "Cash · KHQR / Bakong · card", "built"),
            ("Tips", "Collect + split tips", "built"),
            ("Decrement stock on sale", "Sales auto-reduce inventory", "built"),
            ("Product catalog + modifiers", "Items, variants, add-ons", "planned"),
            ("Receipts", "Print or send digital", "planned"),
            ("Discounts & promos", "% / fixed, happy hour, bundles", "planned"),
            ("Refunds & voids", "With reason + audit", "planned"),
            ("Cash drawer / shift", "Open / close, reconcile the drawer", "planned"),
            ("Tables & orders (F&B)", "Dine-in tabs, kitchen tickets", "idea"),
        ],
    },
    "hr_payroll": {
        "icon": "💼", "title": "HR & payroll",
        "what": "Tracked hours → pay runs, payslips, records — no spreadsheets.",
        "ref": "Gusto · Rippling · Deel", "configure": "/customer/config",
        "options": [
            ("Employee records", "Profiles, roles, seniority, documents", "built"),
            ("Leave balances", "AL / sick / unpaid — accrual + carryover", "built"),
            ("Salary privacy", "Senior+ pay is owner-only", "built"),
            ("Onboarding / offboarding", "New-hire + ex-staff bans / handover", "built"),
            ("Salary / wage structures", "Monthly / daily / hourly + allowances", "planned"),
            ("Pay runs", "Monthly / biweekly / weekly cycles", "planned"),
            ("Payslips", "Auto payslip per staffer per cycle", "planned"),
            ("Deductions & contributions", "NSSF, tax, advances, paybacks", "planned"),
            ("Bank payroll file / NSSF export", "Export for the bank / authority", "planned"),
            ("Contracts & e-sign", "Store + sign documents", "idea"),
        ],
    },
    "coverage": {
        "icon": "🎯", "title": "Coverage / Skills",
        "what": "Never understaffed on a skill — set minimums, get warned.",
        "ref": "Deputy · When I Work (skills + rostering)", "configure": "/expertise",
        "options": [
            ("Skills catalog", "Define the skills / roles you staff for", "built"),
            ("Min coverage per skill", "How many of each skill needed at all times", "built"),
            ("Day / hour overrides", "Raise or lower for peak times / quiet days", "built"),
            ("Skill per staffer", "Tag each staffer's skills", "built"),
            ("Coverage warnings", "Alert when a shift would be under-covered", "planned"),
            ("Auto-schedule by coverage", "Build rosters that meet the minimums", "idea"),
        ],
    },
    "reports": {
        "icon": "📊", "title": "Reports & trends",
        "what": "See who / what / when over time — spot patterns, not just today.",
        "ref": "Salesforce Reports · ServiceNow Perf Analytics · QuickBooks", "configure": "/reports",
        "options": [
            ("Attendance trends", "Check-ins, lateness, on-time % by day", "built"),
            ("Expense reports", "Spend by category / supplier over time", "planned"),
            ("Stock reports", "Usage, waste, slow movers, value", "planned"),
            ("Sales reports", "Revenue, top items, by hour / day", "planned"),
            ("Payroll reports", "Hours, OT, cost by staff", "planned"),
            ("Export", "CSV (built) · PDF", "built"),
            ("Custom reports", "Pick fields + filters", "idea"),
            ("Scheduled / emailed digests", "Daily / weekly summary", "idea"),
        ],
    },
    "ai_assist": {
        "icon": "🤖", "title": "AI assist",
        "what": "Smart suggestions + anomaly alerts — the system watches for you.",
        "ref": "Salesforce Einstein · ServiceNow Now Assist", "configure": "/customer/config",
        "options": [
            ("Receipt / photo reading", "Already powering the accountant read", "built"),
            ("AI-power tier per decision", "Computer (rules) vs AI (model) per feature", "built"),
            ("Anomaly alerts", "Flag a late spike, a price jump, a stockout risk", "idea"),
            ("Suggestions", "'Reorder X' · 'approve this leave — coverage holds'", "idea"),
            ("Forecasting", "Predict busy times + stock needs", "idea"),
            ("Natural-language ask", "'How many late this week?' → answer", "idea"),
        ],
    },
    "automations": {
        "icon": "⚙️", "title": "Automations",
        "what": "Your own if-this-then-that rules — no code.",
        "ref": "Salesforce Flow · ServiceNow Workflow · Zapier", "configure": "/customer/config",
        "options": [
            ("Bot-as-approver", "Auto-decide on coverage / quota rules", "built"),
            ("Re-ping / escalation ladders", "Chase non-responders, escalate to owner", "built"),
            ("Triggers", "On check-in, sale, low-stock, leave request, schedule", "idea"),
            ("Conditions", "If late > N · if coverage < min · if amount > X", "idea"),
            ("Actions", "Notify · approve · create task · adjust", "idea"),
            ("Templates", "Prebuilt common automations to start from", "idea"),
        ],
    },
    "learn": {
        "icon": "🎓", "title": "Learn / Help",
        "what": "Guided how-tos right where you are — no manuals, no training day.",
        "ref": "Salesforce Trailhead · Intercom · Pendo", "configure": "/customer/config",
        "options": [
            ("Contextual help", "Plain-English 'what's this?' on every setting", "built"),
            ("Onboarding checklist", "The setup cards (this dashboard)", "built"),
            ("Guided tours", "Step-by-step walkthroughs in-app", "idea"),
            ("How-to library", "Short articles / videos", "idea"),
            ("Per-industry tips", "Best-practice suggestions for your trade", "idea"),
        ],
    },
    "marketplace": {
        "icon": "🧩", "title": "Marketplace / Integrations",
        "what": "Connect tools you already use — switch on only what you need.",
        "ref": "Shopify App Store · Salesforce AppExchange", "configure": "/customer/config",
        "options": [
            ("Messaging", "Telegram (core) · FB / IG · WhatsApp", "planned"),
            ("Stock", "AppSheet today · our cloud later", "built"),
            ("Accounting", "QuickBooks / Xero sync", "planned"),
            ("Payments", "Bakong / KHQR · ABA · Wing", "planned"),
            ("POS", "Loyverse · Square", "planned"),
            ("Delivery", "FoodPanda · Grab · Nham24", "idea"),
            ("Third-party add-ons", "Open extensions by others", "idea"),
        ],
    },
    "mobile_app": {
        "icon": "📱", "title": "Mobile app",
        "what": "Your own branded app — on top of Telegram + web.",
        "ref": "white-label app builders", "configure": "/customer/config",
        "options": [
            ("Branded staff app", "Check in, requests, schedule", "idea"),
            ("Branded customer app", "Order, loyalty, receipts", "idea"),
            ("Push notifications", "Shift reminders, promos", "idea"),
            ("Offline mode", "Works without signal, syncs later", "idea"),
            ("App-store publishing", "iOS + Android under your brand", "idea"),
        ],
    },
}

# Option name → config path, for options now WIRED as on/off toggles on the card page (config-driven; behavior
# follows per option). Only non-LIVE knobs; the save handler whitelists to these + re-checks editability.
TOGGLES = {
    "accountant": {
        "Food allowance": "categories.accountant.food_money.enabled",
        "Expense categories": "categories.accountant.expense_categories",
        "Invoices & receivables": "categories.accountant.invoices",
        "Bank / cash reconciliation": "categories.accountant.reconciliation",
        "P&L · cash-flow reports": "categories.accountant.financial_reports",
        "Tax / VAT tracking": "categories.accountant.tax_vat",
        "Multi-currency": "categories.accountant.multi_currency",
    },
    "stock": {
        "Par / reorder levels": "categories.stock.par_levels",
        "Supplier price compare": "categories.stock.supplier_price_compare",
        "Low-stock & expiry alerts": "categories.stock.low_stock_alert",
        "Item catalog": "categories.stock.item_catalog",
        "Purchase orders": "categories.stock.purchase_orders",
        "Stock movements": "categories.stock.stock_movements",
        "Barcode / QR": "categories.stock.barcode_qr",
        "Recipes / BOM": "categories.stock.recipes_bom",
        "Valuation": "categories.stock.valuation",
    },
    "pos": {
        "Tips": "categories.pos.tips_enabled",
        "Decrement stock on sale": "categories.pos.track_inventory",
        "Product catalog + modifiers": "categories.pos.product_catalog",
        "Discounts & promos": "categories.pos.discounts",
        "Refunds & voids": "categories.pos.refunds",
        "Cash drawer / shift": "categories.pos.cash_drawer",
        "Tables & orders (F&B)": "categories.pos.tables_orders",
    },
    "hr_payroll": {
        "Salary privacy": "categories.hr_payroll.salary_owner_only",
        "Salary / wage structures": "categories.hr_payroll.wage_structures",
        "Pay runs": "categories.hr_payroll.pay_runs",
        "Payslips": "categories.hr_payroll.payslips",
        "Deductions & contributions": "categories.hr_payroll.deductions",
        "Bank payroll file / NSSF export": "categories.hr_payroll.nssf_export",
        "Contracts & e-sign": "categories.hr_payroll.contracts_esign",
    },
    "coverage": {
        "Min coverage per skill": "categories.attendance.expertise.enabled",
        "Coverage warnings": "categories.attendance.expertise.coverage_warnings",
        "Auto-schedule by coverage": "categories.attendance.expertise.auto_schedule",
    },
    # Frontier-card sub-options (planned/idea) — preview toggles → frontier_options.<key>.<opt>
    "reports": {
        "Expense reports": "frontier_options.reports.expense",
        "Stock reports": "frontier_options.reports.stock",
        "Sales reports": "frontier_options.reports.sales",
        "Payroll reports": "frontier_options.reports.payroll",
        "Custom reports": "frontier_options.reports.custom",
        "Scheduled / emailed digests": "frontier_options.reports.scheduled",
    },
    "ai_assist": {
        "Anomaly alerts": "frontier_options.ai_assist.anomaly",
        "Suggestions": "frontier_options.ai_assist.suggestions",
        "Forecasting": "frontier_options.ai_assist.forecasting",
        "Natural-language ask": "frontier_options.ai_assist.nl_ask",
    },
    "automations": {
        "Triggers": "frontier_options.automations.triggers",
        "Conditions": "frontier_options.automations.conditions",
        "Actions": "frontier_options.automations.actions",
        "Templates": "frontier_options.automations.templates",
    },
    "learn": {
        "Guided tours": "frontier_options.learn.guided_tours",
        "How-to library": "frontier_options.learn.how_to_library",
        "Per-industry tips": "frontier_options.learn.per_industry_tips",
    },
    "marketplace": {
        "Messaging": "frontier_options.marketplace.messaging",
        "Accounting": "frontier_options.marketplace.accounting",
        "Payments": "frontier_options.marketplace.payments",
        "POS": "frontier_options.marketplace.pos",
        "Delivery": "frontier_options.marketplace.delivery",
        "Third-party add-ons": "frontier_options.marketplace.third_party",
    },
    "mobile_app": {
        "Branded staff app": "frontier_options.mobile_app.staff_app",
        "Branded customer app": "frontier_options.mobile_app.customer_app",
        "Push notifications": "frontier_options.mobile_app.push",
        "Offline mode": "frontier_options.mobile_app.offline",
        "App-store publishing": "frontier_options.mobile_app.app_store",
    },
}
