#!/usr/bin/env python3
"""Generate MAP_INDEX.md — Layer 2, the AUTO file inventory.

Two-layer map (2026-06-19):
  - Layer 1 = MAP.md       hand-curated WISDOM (gotchas, laws, entry files + symbols). Slim.
  - Layer 2 = MAP_INDEX.md GENERATED FACTS: every source file -> its docstring + top-level symbols.

Because Layer 2 is generated by walking the filesystem, it is 100% COMPLETE on files and can never
omit a new one or go stale — which dissolves the old MAP-IGNORE hand-classification (the thing that
went wrong on 2026-06-19). Symbol lists are a capped SUMMARY (grep for the exhaustive set).

Usage:
  python scripts/gen_map_index.py            # (re)write MAP_INDEX.md
  python scripts/gen_map_index.py --check     # exit 1 if MAP_INDEX.md is stale (used by the freshness test)
"""
import ast
import glob
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "MAP_INDEX.md")
SYM_CAP = 15
# dirs that are NOT source-code packages (infra / build / docs / tests / venv). Everything else with a .py is.
_EXCLUDE_DIRS = {".git", ".github", ".githooks", ".claude", "__pycache__", "venv", ".venv", "node_modules",
                 "dist", "build", "logs", "docs", "tests", "archive", "audit_anchors", ".pytest_cache",
                 ".idea", ".vscode"}


def pkg_dirs() -> list:
    """Top-level CODE packages = every ROOT dir (not excluded / not dot-prefixed) that contains a .py file.
    Derived from the FILESYSTEM, not a hardcoded list, so a new package can never be silently omitted — the
    very bug-class behind the old MAP_INDEX gap (a value hardcoded in the caller, not read from its source of
    truth, here the filesystem). The integrity test imports THIS so the two can never disagree."""
    out = []
    for name in sorted(os.listdir(ROOT)):
        p = os.path.join(ROOT, name)
        if not os.path.isdir(p) or name.startswith(".") or name in _EXCLUDE_DIRS:
            continue
        if any(f.endswith(".py") for _r, _d, fs in os.walk(p) for f in fs):
            out.append(name)
    return out


def _info(path: str):
    """(one-line docstring, [top-level def/class names]) for a python file — never raises."""
    try:
        with open(path, encoding="utf-8") as f:
            tree = ast.parse(f.read())
    except (SyntaxError, UnicodeDecodeError):
        return "(parse error)", []
    doc = (ast.get_docstring(tree) or "").strip().split("\n")[0]
    syms = [n.name for n in tree.body
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))]
    return doc, syms


def _entry(rel: str) -> list[str]:
    doc, syms = _info(os.path.join(ROOT, rel))
    out = ["- `%s` — %s" % (rel, doc) if doc else "- `%s`" % rel]
    if syms:
        shown = ", ".join(syms[:SYM_CAP]) + ("  …(+%d, grep)" % (len(syms) - SYM_CAP) if len(syms) > SYM_CAP else "")
        out.append("    · %s" % shown)
    return out


def render() -> str:
    L = ["# MAP_INDEX — auto-generated file inventory (Layer 2)",
         "",
         "> **GENERATED by `scripts/gen_map_index.py` — do not edit by hand.** Layer 1 wisdom = `MAP.md`.",
         "> Every source file → its docstring + top-level symbols (capped; grep for the full set).",
         "> Complete-on-files by construction. Regenerate after any file add/move; the build fails if stale.",
         ""]
    for d in pkg_dirs():
        dp = os.path.join(ROOT, d)
        if not os.path.isdir(dp):
            continue
        L.append("## %s/" % d)
        for f in sorted(os.listdir(dp)):
            if f.endswith(".py"):
                L += _entry("%s/%s" % (d, f))
        L.append("")
    # root-level runnable entry points
    roots = sorted(os.path.basename(p) for p in glob.glob(os.path.join(ROOT, "run_*.py")))
    roots += [f for f in ("bootstrap.py",) if os.path.exists(os.path.join(ROOT, f))]
    if roots:
        L.append("## (root entry points)")
        for f in roots:
            L += _entry(f)
        L.append("")
    return "\n".join(L).rstrip() + "\n"


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        cur = ""
        if os.path.exists(OUT):
            with open(OUT, encoding="utf-8") as f:
                cur = f.read()
        # line-ending agnostic (the repo flips LF<->CRLF) so the check is stable, not a false alarm
        if cur.splitlines() != content.splitlines():
            print("MAP_INDEX.md is STALE — run: python scripts/gen_map_index.py")
            return 1
        print("MAP_INDEX.md is fresh")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print("wrote MAP_INDEX.md (%d entries)" % content.count("- `"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
